#ifndef WINDOWPROPERTY_H
#define WINDOWPROPERTY_H

#define HEADER_HEIGHT 30
#define CBUTTON_WIDTH 25
#define CSIGN_SIZE 5

#define MIN_WIDTH CBUTTON_WIDTH
#define MIN_HEIGHT CBUTTON_WIDTH

#define FONT_FAMILY "Gravity.otf"
#define FSIGN_WIDTH 10
#define FSIGN_HEIGHT 18
#define FSIZE 25

#endif